name: Ubuntu Build
on: [push]
jobs:
  Build-64:
    runs-on: ubuntu-18.04
    name: Build on Ubuntu 18.04 64-bit
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: python -m pip install poetry
      - run: sudo apt install portaudio19-dev
      - run: poetry install
      - run: poetry run bash build.sh
  Build-32:
    runs-on: ubuntu-18.04
    name: Build on Ubuntu 18.04 32-bit
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x86'
      - run: python -m pip install poetry
      - run: sudo apt install portaudio19-dev
      - run: poetry install
      - run: poetry run bash build.sh
