name: Ubuntu Build
on: [push]
jobs:
  Build-64:
    runs-on: ubuntu-18.04
    name: Build on Ubuntu 18.04 64-bit
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: python -m pip install poetry
      - run: sudo apt install portaudio19-dev
      - run: poetry install
      - run: poetry run bash build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-ubuntu-64
          path: |
            dist
  Build-Arm:
    runs-on: ubuntu-18.04
    name: Build on Raspbian Lite ARM
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: pguyot/arm-runner-action@v2
        with:
          copy_artifact_path: dist
          commands: |
              sudo apt-get update && sudo apt-get upgrade -y
              sudo apt-get install -y portaudio19-dev python3-pip
              python3 -m pip install poetry
              poetry config experimental.new-installer false
              poetry cache clear --all pypi
              poetry cache clear --all private
              poetry install
              poetry run bash build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-ubuntu-64
          path: |
            dist
