name: Ubuntu Build
on: [push]
jobs:
  Build-64:
    runs-on: ubuntu-18.04
    name: Build on Ubuntu 18.04 64-bit
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: python -m pip install poetry
      - run: sudo apt install portaudio19-dev
      - run: poetry install
      - run: poetry run bash build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-ubuntu-64
          path: |
            dist
  Build-Arm:
    runs-on: ubuntu-18.04
    name: Build on Raspbian Lite ARM
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: pguyot/arm-runner-action@v2
        with:
          copy_artifact_path: dist
          image_additional_mb: 4096
          commands: |
              sudo apt update && sudo apt upgrade -y
              sudo apt install -y python3 \
                  python3-venv \
                  python3-pip \
                  libsdl2-mixer-2.0-0 \
                  libsdl2-image-2.0-0 \
                  libsdl2-2.0-0 \
                  libsdl2-ttf-2.0-0 \
                  python3-gi \
                  gstreamer1.0-tools \
                  gir1.2-gstreamer-1.0 \
                  gir1.2-gst-plugins-base-1.0 \
                  gstreamer1.0-plugins-good \
                  gstreamer1.0-plugins-ugly \
                  gstreamer1.0-plugins-bad \
                  gstreamer1.0-libav
              curl -sSL https://install.python-poetry.org | python3 -
              export PATH="/home/runner/.local/bin:$PATH"
              poetry export --dev -f requirements.txt --output requirements.txt
              python -m pip install -Ur requirements.txt
              bash build.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-ubuntu-64
          path: |
            dist
